
export const courtList = [
    // Supreme Court
    "Supreme Court of Kenya",

    // Court of Appeal
    "Court of Appeal at Nairobi",
    "Court of Appeal at Mombasa",
    "Court of Appeal at Kisumu",
    "Court of Appeal at Nyeri",
    "Court of Appeal at Eldoret",
    "Court of Appeal at Malindi",

    // High Court Divisions
    "High Court - Family Division (Milimani)",
    "High Court - Commercial & Admiralty Division (Milimani)",
    "High Court - Civil Division (Milimani)",
    "High Court - Criminal Division (Milimani)",
    "High Court - Constitutional and Human Rights Division (Milimani)",
    "High Court - Judicial Review Division (Milimani)",
    "High Court - Anti-Corruption & Economic Crimes Division (Milimani)",

    // High Court Stations
    "High Court at Nairobi (Milimani)",
    "High Court at Bungoma",
    "High Court at Busia",
    "High Court at Eldoret",
    "High Court at Embu",
    "High Court at Garissa",
    "High Court at Homa Bay",
    "High Court at Isiolo",
    "High Court at Kajiado",
    "High Court at Kakamega",
    "High Court at Kapenguria",
    "High Court at Kericho",
    "High Court at Kerugoya",
    "High Court at Kiambu",
    "High Court at Kilgoris",
    "High Court at Kisii",
    "High Court at Kisumu",
    "High Court at Kitale",
    "High Court at Kitui",
    "High Court at Kwale",
    "High Court at Lodwar",
    "High Court at Machakos",
    "High Court at Makueni",
    "High Court at Malindi",
    "High Court at Maralal",
    "High Court at Marsabit",
    "High Court at Meru",
    "High Court at Migori",
    "High Court at Mombasa",
    "High Court at Murang'a",
    "High Court at Nakuru",
    "High Court at Nanyuki",
    "High Court at Narok",
    "High Court at Nyahururu",
    "High Court at Nyeri",
    "High Court at Siaya",
    "High Court at Thika",
    "High Court at Vihiga",

    // Employment and Labour Relations Court
    "Employment & Labour Relations Court at Nairobi",
    "Employment & Labour Relations Court at Mombasa",
    "Employment & Labour Relations Court at Kisumu",
    "Employment & Labour Relations Court at Nakuru",
    "Employment & Labour Relations Court at Nyeri",
    "Employment & Labour Relations Court at Eldoret",
    "Employment & Labour Relations Court at Kericho",
    "Employment & Labour Relations Court at Meru",
    "Employment & Labour Relations Court at Malindi",

    // Environment and Land Court
    "Environment & Land Court at Nairobi",
    "Environment & Land Court at Bungoma",
    "Environment & Land Court at Busia",
    "Environment & Land Court at Eldoret",
    "Environment & Land Court at Embu",
    "Environment & Land Court at Garissa",
    "Environment & Land Court at Homa Bay",
    "Environment & Land Court at Isiolo",
    "Environment & Land Court at Kajiado",
    "Environment & Land Court at Kakamega",
    "Environment & Land Court at Kericho",
    "Environment & Land Court at Kerugoya",
    "Environment & Land Court at Kiambu",
    "Environment & Land Court at Kisii",
    "Environment & Land Court at Kisumu",
    "Environment & Land Court at Kitale",
    "Environment & Land Court at Kitui",
    "Environment & Land Court at Machakos",
    "Environment & Land Court at Makueni",
    "Environment & Land Court at Malindi",
    "Environment & Land Court at Meru",
    "Environment & Land Court at Migori",
    "Environment & Land Court at Mombasa",
    "Environment & Land Court at Murang'a",
    "Environment & Land Court at Nakuru",
    "Environment & Land Court at Nanyuki",
    "Environment & Land Court at Narok",
    "Environment & Land Court at Nyahururu",
    "Environment & Land Court at Nyeri",
    "Environment & Land Court at Thika",

    // Chief Magistrates Courts (Major Stations)
    "Chief Magistrate's Court at Milimani (Nairobi)",
    "Chief Magistrate's Court at Makadara (Nairobi)",
    "Chief Magistrate's Court at Kibera (Nairobi)",
    "Chief Magistrate's Court at Mombasa",
    "Chief Magistrate's Court at Kisumu",
    "Chief Magistrate's Court at Eldoret",
    "Chief Magistrate's Court at Nakuru",
    "Chief Magistrate's Court at Nyeri",
    "Chief Magistrate's Court at Kiambu",
    "Chief Magistrate's Court at Thika",

    // Other Courts & Tribunals
    "Kadhis' Court",
    "Courts Martial",
    "Small Claims Court",
    "HIV and AIDS Tribunal",
    "Political Parties Disputes Tribunal",
    "Rent Restriction Tribunal",
    "Business Premises Rent Tribunal",
    "Cooperative Tribunal",
    "National Environment Tribunal",
];
